version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build --configuration RELEASE
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - 'cXMLHandler/bin/Release/netcoreapp2.1/*'