version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish --configuration RELEASE
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - 'cXMLHandler/bin/Release/netcoreapp2.1/publish/*'
  name: 'cXMLHandler.zip'
  discard-paths: yes